basePath: /api/v1
definitions:
  models.Ping:
    properties:
      pong:
        example: 2021-10-31 16:13:58.292387 +0000 UTC
        type: string
    type: object
  models.Product:
    properties:
      brand:
        example: Haribo
        type: string
      id:
        example: "1"
        type: string
      name:
        example: Rotella
        type: string
      price:
        example: 13.9
        type: number
    type: object
host: localhost:8080
info:
  contact:
    name: DELGEHIER Cedric
    url: https://twitter.com/JackNemrod
  description: This is the MyApp API server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: MyApp API
  version: "1.0"
paths:
  /api/v1/ping:
    get:
      consumes:
      - application/json
      description: Ping method for API Server
      produces:
      - application/json
      responses:
        "200":
          description: ping !
          schema:
            $ref: '#/definitions/models.Ping'
      summary: Ping
  /api/v1/products:
    get:
      consumes:
      - application/json
      description: Get a list of all products known
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
      summary: List products
      tags:
      - products
  /api/v1/products/{id}:
    get:
      consumes:
      - application/json
      description: Get a product by its ID
      parameters:
      - description: The ID of the product
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "404":
          description: error
          schema:
            type: string
      summary: Show product by ID
      tags:
      - products
  /api/v1/version:
    get:
      consumes:
      - application/json
      description: Version of API-server
      produces:
      - application/json
      responses:
        "200":
          description: version
          schema:
            type: string
      summary: Version
swagger: "2.0"
